# Generated by Django 5.0.6 on 2024-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="escolaridade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status_escolaridade",
                    models.IntegerField(
                        choices=[
                            (1, "Nenhuma"),
                            (2, "Fundamental Incompleto"),
                            (3, "Fundamental Completo"),
                            (4, "Ensino Médio Incompleto"),
                            (5, "Ensino Médio Completo"),
                            (6, "Ensino Superior Incompleto"),
                            (7, "Ensino Superior Completo"),
                            (8, "Outro"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("rg", models.CharField(max_length=9)),
                ("cpf", models.CharField(max_length=11)),
            ],
        ),
    ]
