# Generated by Django 5.0.6 on 2024-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_escolaridade_pessoa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("especie", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=500)),
            ],
        ),
    ]
