# Generated by Django 5.0.6 on 2024-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_casa_prontuario_animal_nome"),
    ]

    operations = [
        migrations.DeleteModel(
            name="escolaridade",
        ),
        migrations.AddField(
            model_name="pessoa",
            name="status_escolaridade",
            field=models.IntegerField(
                choices=[
                    (1, "Nenhuma"),
                    (2, "Fundamental Incompleto"),
                    (3, "Fundamental Completo"),
                    (4, "Ensino Médio Incompleto"),
                    (5, "Ensino Médio Completo"),
                    (6, "Ensino Superior Incompleto"),
                    (7, "Ensino Superior Completo"),
                    (8, "Outro"),
                ],
                default=1,
            ),
        ),
    ]
