# Generated by Django 5.0.6 on 2024-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_escolaridade_pessoa_status_escolaridade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="cpf",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
