# Generated by Django 5.0.6 on 2024-08-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_pessoa_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="cpf",
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="rg",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
