# Generated by Django 5.0.6 on 2024-08-26 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_pessoa_cpf_alter_pessoa_rg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "casa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casa",
                        to="core.casa",
                    ),
                ),
                (
                    "pessoas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pessoas",
                        to="core.pessoa",
                    ),
                ),
            ],
        ),
    ]
