# Generated by Django 5.0.6 on 2024-08-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_familia"),
    ]

    operations = [
        migrations.AddField(
            model_name="casa",
            name="numero_casa",
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casa",
            name="numero_comodos",
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
