# Generated by Django 5.0.6 on 2024-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_casa_numero_casa_casa_numero_comodos"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="data_nasc",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
