# Generated by Django 5.0.6 on 2024-08-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_pessoa_data_nasc"),
    ]

    operations = [
        migrations.AddField(
            model_name="casa",
            name="data_entrada",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="data_adoeceu",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="data_nasc",
            field=models.DateField(blank=True, null=True),
        ),
    ]
