# Generated by Django 5.1 on 2024-08-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_casa_data_entrada_prontuario_data_adoeceu_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"verbose_name_plural": "Animais"},
        ),
    ]
