# Generated by Django 5.1 on 2024-08-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_animal_fotoanimal"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="fotoPessoa",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
