# Generated by Django 5.1 on 2024-09-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_prontuario_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prontuario",
            name="nome",
        ),
        migrations.AddField(
            model_name="prontuario",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animais",
                to="core.animal",
            ),
        ),
    ]
