# Generated by Django 5.1 on 2024-09-05 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_prontuario_nome_prontuario_animal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prontuario",
            name="animal",
        ),
        migrations.AddField(
            model_name="prontuario",
            name="nome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animal",
                to="core.animal",
            ),
        ),
    ]
