# Generated by Django 5.1 on 2024-09-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_prontuario_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="prontuario",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prontuarios",
                to="core.animal",
            ),
        ),
        migrations.AlterField(
            model_name="prontuario",
            name="nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
