# Generated by Django 5.1 on 2024-09-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_prontuario_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="pessoas",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="pessoas", to="core.pessoa"
            ),
        ),
    ]
