# Generated by Django 5.1 on 2024-09-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_familia_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familia",
            name="nome",
        ),
    ]
