# Generated by Django 5.1 on 2024-10-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_familia_pessoas_familia_pessoas"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Familia",
        ),
    ]
