# Generated by Django 5.1 on 2024-10-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_remove_casa_data_entrada"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="foto",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="uploader.image"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tipo_usuario",
            field=models.IntegerField(
                choices=[(1, "Cliente"), (2, "Vendedor"), (3, "Gerente")], default=1, verbose_name="User Type"
            ),
        ),
    ]
