# Generated by Django 5.1.3 on 2024-12-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_user_foto_user_tipo_usuario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Prontuario",
        ),
    ]
