# Generated by Django 5.1.3 on 2024-12-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_delete_prontuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="descricao",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
